# Generated by Django 5.1.4 on 2024-12-19 03:00

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=255)),
                ('kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('hp_beli', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('h_jual', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('stok', models.IntegerField(default=0)),
                ('total_hp_beli', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_h_jual', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('tgl_terjual', models.DateField(blank=True, null=True)),
                ('tgl_stok_masuk', models.DateField(default=django.utils.timezone.now)),
                ('barcode', models.CharField(blank=True, max_length=13, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Barang',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kasir_kategori',
            },
        ),
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(blank=True, verbose_name='Header Struk')),
                ('footer', models.TextField(blank=True, verbose_name='Footer Struk')),
                ('paper_size', models.CharField(choices=[('58mm', '58mm'), ('80mm', '80mm')], default='58mm', max_length=10)),
                ('show_logo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Struk',
                'verbose_name_plural': 'Pengaturan Struk',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Toko')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('phone', models.CharField(max_length=20, verbose_name='Telepon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Toko',
                'verbose_name_plural': 'Pengaturan Toko',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('IDR', 'Rupiah'), ('USD', 'Dollar')], default='IDR', max_length=10)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20)),
                ('timezone', models.CharField(choices=[('Asia/Jakarta', 'WIB'), ('Asia/Makassar', 'WITA'), ('Asia/Jayapura', 'WIT')], default='Asia/Jakarta', max_length=50)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('enable_email_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Sistem',
                'verbose_name_plural': 'Pengaturan Sistem',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_invoice', models.CharField(max_length=100, unique=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dibayar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kembalian', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBarang',
            fields=[
                ('no', models.CharField(db_index=True, max_length=50)),
                ('nama_barang', models.CharField(max_length=255)),
                ('kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('hp_beli', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('h_jual', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('stok', models.IntegerField(default=0)),
                ('total_hp_beli', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_h_jual', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('tgl_terjual', models.DateField(blank=True, null=True)),
                ('tgl_stok_masuk', models.DateField(default=django.utils.timezone.now)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=13, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical barang',
                'verbose_name_plural': 'historical Barang',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255)),
                ('hp_beli', models.DecimalField(decimal_places=2, max_digits=10)),
                ('h_jual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField(default=0)),
                ('stok_minimal', models.IntegerField(default=0)),
                ('tgl_terjual', models.DateTimeField(blank=True, null=True)),
                ('tgl_stok_masuk', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk_set', to='kasir.kategori')),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
                'db_table': 'kasir_produk',
            },
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasir.produk')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasir.transaksi')),
            ],
        ),
    ]
