# Generated by Django 5.1.4 on 2024-12-19 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='stok_minimal',
        ),
        migrations.AlterField(
            model_name='produk',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasir.kategori'),
        ),
        migrations.AlterModelTable(
            name='produk',
            table=None,
        ),
    ]
