# Generated by Django 5.1.4 on 2024-12-19 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0003_alter_transaksi_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaksidetail',
            options={'verbose_name': 'Detail Transaksi', 'verbose_name_plural': 'Detail Transaksi'},
        ),
        migrations.RemoveField(
            model_name='transaksidetail',
            name='produk',
        ),
        migrations.AddField(
            model_name='transaksidetail',
            name='barang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasir.barang'),
        ),
    ]
