# Generated by Django 5.1.4 on 2024-12-19 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0004_alter_transaksidetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksidetail',
            name='barang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasir.produk'),
        ),
    ]
