# Generated by Django 5.1.4 on 2024-12-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0006_receiptsettings_printer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=1)),
                ('template', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('access_admin', models.BooleanField(default=True)),
                ('access_kasir', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
